flowchart TB
    subgraph AI[Artificial Intelligence]
        subgraph ML[Machine Learning]
            subgraph NN[Neural Networks]
                subgraph DL[Deep Learning]
                   GA[Generative AI]
                end
            end
        end
    end

    style AI fill:#d0d0d0,stroke:#000000,stroke-width:2px
    style ML fill:#00d0d0,stroke:#000000,stroke-width:2px
    style NN fill:#d000d0,stroke:#000000,stroke-width:2px
    style DL fill:#00d000,stroke:#000000,stroke-width:2px
    style GA fill:#d00000,stroke:#000000,stroke-width:2px
